"""Prose that quotes a generated artifact, held to the artifact.

``docs/audits/eval-report.json`` is regenerated by ``make eval`` and compared by
``make eval-check``, so the numbers in it are what the recommender produces.
Two documents then quote those numbers by hand:

* ``docs/audits/source-ethics.md`` has a Precision/Recall/MAP table for the
  content model and the popularity baseline, and says underneath that it was
  "Regenerated into ``docs/audits/eval-report.json`` by ``make eval``".
* ``docs/USER-RESEARCH.md`` repeats the same figures in Dr. Ada's persona, as
  the values the recommender is trusted to hold.

Nothing read either. The chain ran code, artifact, prose, and was gated only on
its first link: the report could be regenerated correctly on every run while the
two documents kept quoting whatever the numbers used to be. That is how a
"257-test suite" survives in a paper against a suite of a thousand.

The figures are now read out of the artifact. ``docs/audits/coverage.xml`` is held by
``scripts/coverage_check.py`` instead, for the reasons stated there.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EVAL_REPORT = REPO_ROOT / "docs" / "audits" / "eval-report.json"
SOURCE_ETHICS = REPO_ROOT / "docs" / "audits" / "source-ethics.md"
USER_RESEARCH = REPO_ROOT / "docs" / "USER-RESEARCH.md"


def _report() -> dict[str, object]:
    assert EVAL_REPORT.is_file(), f"{EVAL_REPORT} is missing; run `make eval`"
    loaded = json.loads(EVAL_REPORT.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict)
    return loaded


def _model(name: str) -> dict[str, float]:
    models = _report()["models"]
    assert isinstance(models, dict), "eval-report.json has no models mapping"
    assert name in models, f"eval-report.json no longer reports the {name} model"
    scores = models[name]
    assert isinstance(scores, dict)
    return {key: float(value) for key, value in scores.items() if isinstance(value, int | float)}


def _two_decimals(value: float) -> str:
    """``0.4`` as ``"0.40"``, which is how both documents write these figures."""
    return f"{value:.2f}"


def test_the_source_ethics_table_quotes_the_committed_eval_report() -> None:
    """Both rows of the table, cell by cell, against the artifact it names."""
    text = SOURCE_ETHICS.read_text(encoding="utf-8")
    rows = {
        "content (themes + authors + curated lists)": _model("content"),
        "popularity baseline": _model("popularity"),
    }
    for label, scores in rows.items():
        pattern = re.compile(
            r"^\| " + re.escape(label) + r" \| ([0-9.]+) \| ([0-9.]+) \| ([0-9.]+) \|$",
            re.MULTILINE,
        )
        found = pattern.findall(text)
        assert len(found) == 1, (
            f"{SOURCE_ETHICS.name} no longer has exactly one row for {label!r}; "
            "the table this test reads has moved or changed shape"
        )
        precision, recall, map_at_k = found[0]
        expected = (
            _two_decimals(scores["precision_at_k"]),
            _two_decimals(scores["recall_at_k"]),
            _two_decimals(scores["map_at_k"]),
        )
        assert (precision, recall, map_at_k) == expected, (
            f"{SOURCE_ETHICS.name} states {(precision, recall, map_at_k)} for "
            f"{label!r}, but eval-report.json holds {expected}. The document "
            "quotes an artifact it no longer matches"
        )


def test_user_research_quotes_the_committed_popularity_baseline() -> None:
    """Dr. Ada's persona carries the same three numbers, written `a / b / c`."""
    text = re.sub(r"\s+", " ", USER_RESEARCH.read_text(encoding="utf-8"))
    found = re.findall(r"a popularity baseline at ([0-9.]+) / ([0-9.]+) / ([0-9.]+)", text)
    assert len(found) == 1, (
        f"{USER_RESEARCH.name} no longer states the popularity baseline in the "
        "form this test reads. The figure is the reason the sentence is there"
    )
    popularity = _model("popularity")
    expected = (
        _two_decimals(popularity["precision_at_k"]),
        _two_decimals(popularity["recall_at_k"]),
        _two_decimals(popularity["map_at_k"]),
    )
    assert found[0] == expected, (
        f"{USER_RESEARCH.name} states {found[0]} for the popularity baseline, "
        f"but eval-report.json holds {expected}"
    )


def test_user_research_quotes_the_committed_content_model_score() -> None:
    text = re.sub(r"\s+", " ", USER_RESEARCH.read_text(encoding="utf-8"))
    found = re.findall(r"Precision@5 / Recall@5 / MAP@5 = ([0-9.]+)", text)
    assert len(found) == 1, f"{USER_RESEARCH.name} no longer states the content model's score"
    content = _model("content")
    assert {content["precision_at_k"], content["recall_at_k"], content["map_at_k"]} == {
        float(found[0])
    }, (
        f"{USER_RESEARCH.name} states {found[0]} for all three content metrics, "
        "but eval-report.json no longer has them equal at that value"
    )
